config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :autonomous_system, path: 'asn', param: :asn, only: [:index, :show]
  resources :country, param: :country_iso_code, only: [:index, :show]
  resources :from_headers, param: :domain , only: [:index, :show], constraints: { domain: /[^\/]+/ }
  resources :record, only: [:index, :show]
  resources :report, only: [:index, :show]
  resources :networks, except: [:show]
  resources :search, only: [:new]
  get 'search/results', to: 'search#results', as: :results_search
  get '/admin', to: 'admin#index', format: false
  scope :admin do
    resources :users
    resources :secure_creds, format: false, except: :show
    resources :services, format: false, except: :show do
      member do
        post :test_service
      end
    end
    resources :networks, format: false, except: :show
  end

  resource :charts do
    member do
      get 'asn_summary'
      get 'country_summary'
      get 'dkim_stats_by_asn'
      get 'dkim_stats_by_country'
      get 'dkim_summary'
      get 'dmarc_actual_summary'
      get 'dmarc_predicted_summary'
      get 'dmarc_status_summary'
      get 'header_from_summary'
      get 'spf_stats_by_asn'
      get 'spf_stats_by_country'
      get 'spf_summary'
      get 'top_asn'
    end
  end
end

app/views/admin/_footer.html.haml
.btn-group{role: "group"}
  %button.btn.btn-default{type: "button"} Secure Creds
  %button.btn.btn-default{type: "button"} Services

app/views/admin/index.html.haml
%html
  %head
    = stylesheet_link_tag 'https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js'
    = javascript_include_tag params[:controller]

%h1 Admin

.div.container.col-sm-12
  %ul.nav.nav-tabs
    %li.active
      %a{href: "#secure_creds", data: {toggle: "tab"} } Secure Credentials
    %li
      %a{href: "#services", data: {toggle: "tab"} } Services
    %li
      %a{href: "#networks", data: {toggle: "tab"} } Networks
  .tab-content
    .tab-pane.active.clearfix{id: "secure_creds"}
      .table-wrapper
        .button-toolbar.top-buffer.bottom-buffer
          %a.btn.btn-success{role: "button", href: "#{new_secure_cred_path.html_safe}"}
            %span.glyphicon.glyphicon-plus
            Add New Secure Cred
        %table.table.compact.table-striped.order-column#secure-creds-table
          %thead
            %tr
              %td
                Tag
              %td
                UserName
              %td
                Actions
          %tbody
            - @secure_creds.each do |secure_cred|
              %tr
                %td
                  =secure_cred.tag
                %td
                  =secure_cred.username
                %td
                  %a.btn.btn-primary{role: "button", href: "#{edit_secure_cred_path(secure_cred)}"}
                    %span.glyphicon.glyphicon-pencil
                    Edit
                  = link_to secure_cred, method: :delete, data: {confirm: "Are you sure?", "original-title": "Delete"}, class: "btn btn-danger" do
                    %span.glyphicon.glyphicon-remove
                    Delete
    .tab-pane.clearfix{id: "services"}
      .table-wrapper
        .button-toolbar.top-buffer.bottom-buffer
          %a.btn.btn-success{role: "button", href: "#{new_service_path.html_safe}"}
            %span.glyphicon.glyphicon-plus
            Add New Service

        %table.table.compact.table-striped.order-column#services-table
          %thead
            %tr
              %td
                Tag
              %td
                Host
              %td
                Port
              %td
                Protocol
              %td
                Secure Cred
              %td
                Active?
              %td
                Actions

          %tbody
            - @services.each do |service|
              %tr
                %td
                  =service.tag
                %td
                  =service.host
                %td
                  =service.port
                %td
                  =service.protocol
                %td
                  =SecureCred.find(service.secure_cred_id).username
                %td
                  =service.active
                %td
                  %a.btn.btn-primary{role: "button", href: "#{edit_service_path(service)}"}
                    %span.glyphicon.glyphicon-pencil
                    Edit
                  = link_to service, method: :delete, data: {confirm: "Are you sure?", "original-title": "Delete"}, class: "btn btn-danger" do
                    %span.glyphicon.glyphicon-remove
                    Delete
    .tab-pane.clearfix{id: "networks"}
      .table-wrapper
        .button-toolbar.top-buffer.bottom-buffer
          %a.btn.btn-success{role: "button", href: "#{new_network_path.html_safe}"}
            %span.glyphicon.glyphicon-plus
            Add New Network
        %table.table.compact.table-striped.order-column#networks-table
          %thead
            %tr
              %td
                Network
              %td
                Name
              %td
                Status
              %td
                Source
              %td
                Actions

          %tbody
            - @networks.each do |network|
              %tr
                %td
                  ="#{network.cidr.to_s}/#{network.cidr.prefix}"
                %td
                  =network.display_name
                %td
                  =network.status
                %td
                  =network.source.humanize
                %td
                  %a.btn.btn-primary{role: "button", href: "#{edit_network_path(network)}"}
                    %span.glyphicon.glyphicon-pencil
                    Edit
                  = link_to network, method: :delete, data: {confirm: "Are you sure?", "original-title": "Delete"}, class: "btn btn-danger" do
                    %span.glyphicon.glyphicon-remove
                    Delete