config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :autonomous_system, path: 'asn', param: :asn, only: [:index, :show]
  resources :country, param: :country_iso_code, only: [:index, :show]
  resources :from_headers, param: :domain , only: [:index, :show], constraints: { domain: /[^\/]+/ }
  resources :record, only: [:index, :show]
  resources :report, only: [:index, :show]
  resources :networks, except: [:show]
  resources :search, only: [:new]
  get 'search/results', to: 'search#results', as: :results_search
  get '/admin', to: 'admin#index', format: false
  scope :admin do
    resources :users
    resources :secure_creds, format: false, except: :show
    resources :services, format: false, except: :show do
      member do
        post :test_service
      end
    end
    resources :networks, format: false, except: :show
  end

  resource :charts do
    member do
      get 'asn_summary'
      get 'country_summary'
      get 'dkim_stats_by_asn'
      get 'dkim_stats_by_country'
      get 'dkim_summary'
      get 'dmarc_actual_summary'
      get 'dmarc_predicted_summary'
      get 'dmarc_status_summary'
      get 'header_from_summary'
      get 'spf_stats_by_asn'
      get 'spf_stats_by_country'
      get 'spf_summary'
      get 'top_asn'
    end
  end
end

app/controllers/from_headers_controller.rb
class FromHeadersController < ApplicationController
  def index
    #@from_headers_spf_pass = Record.where(spf: 'pass').group(:header_from).pluck(:header_from, Arel.sql('sum(count)'))
    #@from_headers_spf_fail = Record.where(spf: 'fail').group(:header_from).pluck(:header_from, Arel.sql('sum(count)'))
    #@from_headers_dkim_pass = Record.where(spf: 'pass').group(:header_from).pluck(:header_from, Arel.sql('sum(count)'))
    #@from_headers_dkim_fail = Record.where(spf: 'fail').group(:header_from).pluck(:header_from, Arel.sql('sum(count)'))
    records = Record.group(:header_from, :spf, :dkim).pluck(:header_from, :spf, :dkim, Arel.sql('sum(count)'))
    @from_headers = {}
    records.each do |domain, spf, dkim, count|
      if not @from_headers.key?(domain)
        @from_headers[domain] = HashWithIndifferentAccess.new({
          'dmarc_pass': 0,
          'dmarc_fail': 0,
          'spf_pass': 0,
          'spf_fail': 0,
          'dkim_pass': 0,
          'dkim_fail': 0,
          'total': 0
        })
      end
      @from_headers[domain]["spf_#{spf}"] += count
      @from_headers[domain]["dkim_#{dkim}"] += count
      if spf == 'fail' and dkim == 'fail'
        @from_headers[domain]['dmarc_fail'] += count
      else
        @from_headers[domain]['dmarc_pass'] += count
      end
      @from_headers[domain]['total'] += count
    end
  end

  def show
    @records = Record.where(header_from: params[:domain]).take
  end
end

app/helpers/from_headers_helper.rb
module FromHeadersHelper
end

app/views/from_headers/_searchbar.html.haml
%form.navbar-form{role: "search", style: "display:inline-block;"}
  .form-group.input-group
    %input.form-control{type: "search", placeholder: "Search", id: "#{custom_id}", class: "#{custom_class}", data: {spf: "#{data_spf}", dkim: "#{data_dkim}"}}

app/views/from_headers/index.html.haml
%html
  %head
    = stylesheet_link_tag 'https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js'
    = javascript_include_tag params[:controller]

%h1 From Headers
.table-wrapper.bordered
  %table.table.table-condensed.table-striped.table-bordered.order-column#from-headers
    %thead
      %tr
        %td
          From Header
        %td
          DMARC Pass
        %td
          DMARC Fail
        %td
          SPF Pass
        %td
          SPF Fail
        %td
          DKIM Pass
        %td
          DKIM Fail
        %td
          Total
    %tbody
      - @from_headers.keys.each do |domain|
        %tr
          %td
            =link_to(domain, "#{from_headers_url}/#{domain}")
          %td
            =@from_headers[domain]['dmarc_pass']
          %td
            =@from_headers[domain]['dmarc_fail']
          %td
            =@from_headers[domain]['spf_pass']
          %td
            =@from_headers[domain]['spf_fail']
          %td
            =@from_headers[domain]['dkim_pass']
          %td
            =@from_headers[domain]['dkim_fail']
          %td
            =@from_headers[domain]['total']

app/views/from_headers/show.html.haml
%html
  %head
    = stylesheet_link_tag 'https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css'
    = javascript_include_tag 'https://www.gstatic.com/charts/loader.js'
    = javascript_include_tag('home.js')
    = javascript_include_tag 'https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js'
%h1
  = params[:domain]
%div.chart-wrapper.bordered.clearfix
  = render partial: "home/summaries" ,
    locals: { context: params[:controller],
      dmarc_actual_path: dmarc_actual_summary_charts_path(header_from: params[:domain]),
      dmarc_predicted_path: dmarc_predicted_summary_charts_path(header_from: params[:domain]),
      spf_summary_path: spf_summary_charts_path(header_from: params[:domain]),
      dkim_summary_path: dkim_summary_charts_path(header_from: params[:domain]),
      header_from_summary_path: header_from_summary_charts_path(header_from: params[:domain]),
      asn_summary_path: asn_summary_charts_path(header_from: params[:domain]),
      country_summary_path: country_summary_charts_path(header_from: params[:domain]) }